import { Producto, Categoria } from './types'

// ─────────────────────────────────────────────────────────────────
// NOTA DE PRECISIÓN
// Los beneficios, costos y condiciones son referenciales.
// Las tasas (TNA/CFT), rendimientos y precios cambian frecuentemente.
// Siempre verificar condiciones vigentes con la entidad financiera.
// ─────────────────────────────────────────────────────────────────

export const CATEGORIAS: Categoria[] = [
  { id: '1', nombre: 'Tarjetas de Crédito', slug: 'tarjetas',    descripcion: 'Encontrá la tarjeta con más beneficios para tu perfil', icono: '💳', color: '#1DB954', cantidad_productos: 12 },
  { id: '2', nombre: 'Cuentas Bancarias',   slug: 'cuentas',     descripcion: 'Cuentas con cashback, sin comisión y con rendimiento',  icono: '🏦', color: '#0ea5e9', cantidad_productos: 10 },
  { id: '3', nombre: 'Préstamos',           slug: 'prestamos',   descripcion: 'Compará tasas y condiciones de los mejores préstamos',  icono: '💰', color: '#f59e0b', cantidad_productos: 8  },
  { id: '4', nombre: 'Seguros',             slug: 'seguros',     descripcion: 'Auto, hogar y vida al mejor precio del mercado',       icono: '🛡️', color: '#6366f1', cantidad_productos: 7  },
  { id: '5', nombre: 'Inversiones',         slug: 'inversiones', descripcion: 'Plazos fijos, FCI y opciones para hacer rendir tu plata', icono: '📈', color: '#ec4899', cantidad_productos: 12 },
  { id: '6', nombre: 'Billeteras Virtuales', slug: 'billeteras',  descripcion: 'Mercado Pago, Ualá, Naranja X y más comparadas',      icono: '📱', color: '#8b5cf6', cantidad_productos: 9  },
]

// ─────────────────────────────────────────────────────────────────
// TARJETAS DE CRÉDITO
// Fuentes: sitios oficiales de cada banco/emisor
// ─────────────────────────────────────────────────────────────────
export const TARJETAS_MOCK: Producto[] = [
  {
    id: 't1',
    categoria: 'tarjetas',
    nombre: 'Visa Signature',
    banco: 'ICBC Argentina',
    logo_domain: 'icbc.com.ar',
    descripcion: 'Tarjeta de alta gama con acceso a salas VIP en aeropuertos del mundo y cobertura de viaje incluida. Ideal para viajeros frecuentes.',
    puntuacion: 9.4,
    beneficios: [
      'Acceso a salas VIP LoungeKey en aeropuertos',
      'Puntos ICBC por cada compra, locales e internacionales',
      'Seguro de viaje automático al pagar pasajes',
      'Cuotas sin interés en comercios adheridos',
      'Compras en cuotas en el exterior',
      'Asistencia al viajero 24hs',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Mejor para viajes',
    beneficio_principal: 'Acceso a salas VIP LoungeKey en aeropuertos',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Consultar con ICBC',
  },
  {
    id: 't2',
    categoria: 'tarjetas',
    nombre: 'Mastercard Black',
    banco: 'Banco Galicia',
    logo_domain: 'galicia.com.ar',
    descripcion: 'La tarjeta más completa de Galicia con cashback, acceso a salas VIP y los mejores descuentos en gastronomía y entretenimiento.',
    puntuacion: 9.2,
    beneficios: [
      'Cashback en compras seleccionadas (% según campaña vigente)',
      'Acceso a salas VIP en aeropuertos',
      'Puntos Galicia que se canjean por productos y viajes',
      'Descuentos en plataformas de streaming',
      'Cuotas sin interés en más de 600 comercios',
      'Asistencia al viajero internacional',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Mastercard',
    tag: 'Más beneficios',
    beneficio_principal: 'Cashback y puntos Galicia en todas las compras',
    cuotas_sin_interes: 'Hasta 18 cuotas s/i',
    ingreso_minimo: 'Consultar con Galicia',
  },
  {
    id: 't3',
    categoria: 'tarjetas',
    nombre: 'Visa Black',
    banco: 'BBVA Argentina',
    logo_domain: 'bbva.com.ar',
    descripcion: 'La tarjeta premium de BBVA con acceso a experiencias exclusivas, seguro de viaje y beneficios en más de 1000 comercios adheridos.',
    puntuacion: 9.0,
    beneficios: [
      'Acceso a salas VIP Priority Pass',
      'Seguro de compra y garantía extendida',
      'Puntos BBVA canjeables en viajes y productos',
      'Cuotas sin interés en comercios adheridos',
      'Descuentos exclusivos en hoteles y vuelos',
      'Asistencia al viajero 24hs',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Premium',
    beneficio_principal: 'Priority Pass — salas VIP en el mundo',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Consultar con BBVA',
  },
  {
    id: 't4',
    categoria: 'tarjetas',
    nombre: 'Amex Platinum',
    banco: 'American Express',
    logo_domain: 'americanexpress.com',
    descripcion: 'La tarjeta de carga más exclusiva del mercado. Sin límite de crédito preestablecido y con los mayores beneficios para el viajero frecuente.',
    puntuacion: 9.6,
    beneficios: [
      'Acceso ilimitado a salas VIP en Argentina y el mundo',
      'Programa de puntos Membership Rewards',
      'Concierge personal 24hs',
      'Seguro de viaje, equipaje y compra',
      'Upgrades preferenciales en hoteles y vuelos',
      'Sin límite de crédito preestablecido',
    ],
    costo_mensual: 8500,
    url_afiliado: '#',
    activo: true,
    red: 'Amex',
    tag: 'Ultra premium',
    beneficio_principal: 'Salas VIP ilimitadas + Concierge personal 24hs',
    cuotas_sin_interes: 'Consultar con Amex',
    ingreso_minimo: 'Consultar con Amex',
  },
  {
    id: 't5',
    categoria: 'tarjetas',
    nombre: 'Amex Gold',
    banco: 'American Express',
    logo_domain: 'americanexpress.com',
    descripcion: 'La versión intermedia de Amex con beneficios en gastronomía, viajes y un programa de puntos de los más completos del mercado.',
    puntuacion: 8.9,
    beneficios: [
      'Puntos Membership Rewards en todas las compras',
      'Descuentos en restaurantes adheridos',
      'Acceso preferencial a salas VIP (con costo)',
      'Seguro de viaje incluido',
      'Cuotas especiales en temporada de viajes',
      'App Amex con gestión completa',
    ],
    costo_mensual: 4200,
    url_afiliado: '#',
    activo: true,
    red: 'Amex',
    tag: 'Para viajes y gastronomía',
    beneficio_principal: 'Membership Rewards en gastronomía y viajes',
    cuotas_sin_interes: 'Consultar con Amex',
    ingreso_minimo: 'Consultar con Amex',
  },
  {
    id: 't6',
    categoria: 'tarjetas',
    nombre: 'Advance Mastercard',
    banco: 'HSBC Argentina',
    logo_domain: 'hsbc.com',
    descripcion: 'Tarjeta del segmento Advance de HSBC con beneficios diferenciales para clientes de perfil medio-alto y acceso a productos del banco.',
    puntuacion: 8.7,
    beneficios: [
      'Descuentos en más de 300 comercios adheridos',
      'Cuotas sin interés en comercios HSBC',
      'Puntos canjeables en el programa de beneficios',
      'Descuentos en seguros del banco',
      'Acceso preferencial a créditos hipotecarios',
      'Banca digital completa',
    ],
    costo_mensual: 2100,
    url_afiliado: '#',
    activo: true,
    red: 'Mastercard',
    tag: 'Banca preferencial',
    beneficio_principal: 'Descuentos en más de 300 comercios HSBC',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Consultar con HSBC',
  },
  {
    id: 't7',
    categoria: 'tarjetas',
    nombre: 'Selecta Visa',
    banco: 'Banco Macro',
    logo_domain: 'macro.com.ar',
    descripcion: 'Tarjeta de primera categoría de Macro con descuentos en combustible, supermercados y acceso al programa de beneficios del banco.',
    puntuacion: 8.5,
    beneficios: [
      'Descuentos en YPF y Shell adheridos',
      'Descuentos en supermercados los fines de semana',
      'Cuotas sin interés en comercios seleccionados',
      'Puntos Macro canjeables',
      'Acceso a créditos preaprobados',
      'Red de cajeros más grande del interior',
    ],
    costo_mensual: 1800,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Descuentos en combustible',
    beneficio_principal: 'Descuentos en YPF, Shell y supermercados',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Consultar con Macro',
  },
  {
    id: 't8',
    categoria: 'tarjetas',
    nombre: 'Naranja X Visa',
    banco: 'Naranja X',
    logo_domain: 'naranjax.com',
    descripcion: 'La tarjeta de crédito digital sin costo, con descuentos en miles de comercios y cuotas en prácticamente todos los negocios adheridos.',
    puntuacion: 8.7,
    beneficios: [
      'Sin costo de mantenimiento ni emisión',
      'Descuentos en más de 200 comercios adheridos',
      'Cuotas en todos los comercios de la red Naranja',
      'App Naranja X con gestión completa',
      'Reintegros en combustible (según campaña)',
      'Compras en cuotas sin interés en comercios seleccionados',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Sin costo',
    beneficio_principal: 'Sin costo — descuentos en 200+ comercios adheridos',
    cuotas_sin_interes: 'Hasta 24 cuotas s/i en red Naranja',
    ingreso_minimo: 'Sin ingreso mínimo',
  },
  {
    id: 't9',
    categoria: 'tarjetas',
    nombre: 'Visa Clásica',
    banco: 'Santander Argentina',
    logo_domain: 'santander.com.ar',
    descripcion: 'La tarjeta de entrada de Santander con acceso a la red de comercios y cuotas sin interés en los programas AHORA del gobierno.',
    puntuacion: 8.2,
    beneficios: [
      'Cuotas sin interés en programas AHORA 3/6/12/18',
      'Descuentos en supermercados y farmacias adheridas',
      'Débito automático de servicios sin cargo',
      'App Santander con gestión completa',
      'Acceso a créditos preaprobados',
      'Red de más de 1.800 cajeros',
    ],
    costo_mensual: 1200,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Para empezar',
    beneficio_principal: 'Programas AHORA 3 / 6 / 12 / 18 cuotas',
    cuotas_sin_interes: 'Hasta 18 cuotas AHORA',
    ingreso_minimo: 'Consultar con Santander',
  },
  {
    id: 't10',
    categoria: 'tarjetas',
    nombre: 'Visa Provincia',
    banco: 'Banco Provincia',
    logo_domain: 'bancoprovincia.com.ar',
    descripcion: 'Tarjeta del banco más grande de la Provincia de Buenos Aires. Ideal para cobrar haberes y acceder a financiación con tasas preferenciales.',
    puntuacion: 7.9,
    beneficios: [
      'Tasas preferenciales para empleados públicos PBA',
      'Cuotas sin interés en comercios adheridos',
      'Acceso a préstamos hipotecarios Provincia',
      'Descuentos en comercios de la red BPS',
      'Red de cajeros en toda la provincia',
      'Cuenta sueldo gratuita',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Empleados públicos PBA',
    beneficio_principal: 'Tasas preferenciales para empleados públicos PBA',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Para empleados públicos PBA',
  },
  {
    id: 't11',
    categoria: 'tarjetas',
    nombre: 'Mastercard Prepaga',
    banco: 'Ualá',
    logo_domain: 'uala.com.ar',
    descripcion: 'Tarjeta prepaga Mastercard sin banco, sin costo y con control total desde la app. Acepta Cuotas Ahora y funciona en comercios y online.',
    puntuacion: 8.5,
    beneficios: [
      'Sin costo de emisión ni mantenimiento',
      'Recarga instantánea desde cualquier banco',
      'Acepta programas AHORA 3/6/12/18',
      'Compras online y en el exterior',
      'Control de gastos en tiempo real',
      'Inversión automática en FCI desde la app',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Mastercard',
    tag: 'Sin banco',
    beneficio_principal: 'Sin banco, sin costos — acepta programas AHORA',
    cuotas_sin_interes: 'Acepta AHORA 3/6/12/18',
    ingreso_minimo: 'Sin ingreso mínimo',
  },
  {
    id: 't12',
    categoria: 'tarjetas',
    nombre: 'Visa Lemon',
    banco: 'Lemon Cash',
    logo_domain: 'lemoncash.app',
    descripcion: 'La primera tarjeta de crédito en Argentina que permite pagar con cripto y pesos, con cashback en USDT en cada compra.',
    puntuacion: 8.3,
    beneficios: [
      'Cashback en USDT en todas las compras',
      'Pago con cripto o pesos indistintamente',
      'Sin costo de mantenimiento',
      'Funciona en cualquier comercio con Visa',
      'App con portfolio de criptomonedas integrado',
      'Cuotas en comercios adheridos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Cashback en cripto',
    beneficio_principal: 'Cashback en USDT en cada compra',
    cuotas_sin_interes: 'Hasta 12 cuotas s/i',
    ingreso_minimo: 'Sin ingreso mínimo',
  },
]

// ─────────────────────────────────────────────────────────────────
// CUENTAS BANCARIAS Y BILLETERAS
// ─────────────────────────────────────────────────────────────────
export const CUENTAS_MOCK: Producto[] = [
  {
    id: 'c1',
    categoria: 'cuentas',
    nombre: 'Cuenta Mercado Pago',
    banco: 'Mercado Pago',
    logo_domain: 'mercadopago.com',
    descripcion: 'La billetera digital más usada de Argentina. Rendimiento diario automático, cashback con QR y acceso a todos los servicios del ecosistema Mercado Libre.',
    puntuacion: 9.3,
    beneficios: [
      'Rendimiento diario automático sobre el saldo (tasa variable)',
      'Cashback en compras con código QR en comercios',
      'Sin costo de apertura ni mantenimiento',
      'Tarjeta Mercado Pago Visa (débito y prepaga)',
      'Transferencias 24/7 a cualquier CBU/CVU',
      'Pago de servicios, impuestos y recarga de celular',
      'Acceso a Mercado Crédito y Mercado Fondos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Más popular',
  },
  {
    id: 'c2',
    categoria: 'cuentas',
    nombre: 'Cuenta Ualá',
    banco: 'Ualá',
    logo_domain: 'uala.com.ar',
    descripcion: 'Cuenta 100% digital con rendimiento sobre el saldo, tarjeta Mastercard sin costo y acceso a inversiones en FCI desde la app.',
    puntuacion: 8.9,
    beneficios: [
      'Rendimiento diario sobre saldo disponible (tasa variable)',
      'Tarjeta Mastercard prepaga sin costo',
      'Apertura 100% online, sin ir al banco',
      'Transferencias CBU/CVU sin límite horario',
      'Inversión en FCI desde la app',
      'Préstamos personales y adelanto de sueldo',
      'Descuentos en Ualá Market',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Sin banco',
  },
  {
    id: 'c3',
    categoria: 'cuentas',
    nombre: 'Cuenta Move',
    banco: 'Banco Galicia',
    logo_domain: 'galicia.com.ar',
    descripcion: 'Cuenta digital del banco privado líder de Argentina. Cero costo, puntos Galicia y acceso completo al ecosistema bancario.',
    puntuacion: 8.8,
    beneficios: [
      'Sin costo de apertura ni mantenimiento',
      'Puntos Galicia en todas las compras con débito',
      'Acceso a tarjetas de crédito y préstamos preaprobados',
      'App Galicia con transferencias, pagos y recarga',
      'Inversión en FCI Galicia desde la app',
      'Descuentos en más de 600 comercios adheridos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco privado',
  },
  {
    id: 'c4',
    categoria: 'cuentas',
    nombre: 'Cuenta BBVA',
    banco: 'BBVA Argentina',
    logo_domain: 'bbva.com.ar',
    descripcion: 'Cuenta digital del banco multinacional con cashback en débito, acceso a créditos preaprobados y experiencia digital de primer nivel.',
    puntuacion: 8.6,
    beneficios: [
      'Sin costo de mantenimiento para salario domiciliado',
      'Cashback en compras seleccionadas (% según campaña)',
      'App BBVA con funcionalidad completa',
      'Acceso a créditos hipotecarios y personales',
      'Inversión en FCI desde homebanking',
      'Más de 1.000 cajeros propios y Red Link',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco multinacional',
  },
  {
    id: 'c5',
    categoria: 'cuentas',
    nombre: 'Cuenta Personal Pay',
    banco: 'Personal Pay',
    logo_domain: 'personalpay.com.ar',
    descripcion: 'La billetera digital de Telecom Argentina. Rendimiento diario, gigas de regalo con Personal y beneficios en el ecosistema Flow.',
    puntuacion: 8.2,
    beneficios: [
      'Rendimiento diario sobre saldo (tasa variable)',
      'Sin costo de apertura ni mantenimiento',
      'Gigas de regalo en servicios Personal',
      'Descuentos en Personal Flow y Arnet',
      'Recarga de celular directa desde la app',
      'Pago de servicios e impuestos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Ecosistema Telecom',
  },
  {
    id: 'c6',
    categoria: 'cuentas',
    nombre: 'BNA+',
    banco: 'Banco Nación',
    logo_domain: 'bna.com.ar',
    descripcion: 'La cuenta digital del banco más grande de Argentina. Ideal para cobrar haberes, jubilaciones y acceder a líneas de crédito preferenciales del Estado.',
    puntuacion: 8.0,
    beneficios: [
      'Sin costo para cuentas sueldo y jubilación',
      'Acceso a créditos hipotecarios Casa Propia',
      'Tasa preferencial para jubilados y pensionados',
      'Red de cajeros más grande del país (más de 1.500)',
      'Pago de impuestos AFIP desde la app',
      'Transferencias DEBIN y CVU sin costo',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco estatal',
  },
  {
    id: 'c7',
    categoria: 'cuentas',
    nombre: 'Cuenta Brubank',
    banco: 'Brubank',
    logo_domain: 'brubank.com',
    descripcion: 'El primer banco 100% mobile de Argentina, con una de las tasas más altas en caja de ahorro y apertura en minutos desde el celular.',
    puntuacion: 8.7,
    beneficios: [
      'Caja de ahorro remunerada con tasa competitiva (variable)',
      'Sin costos de ningún tipo',
      'Apertura 100% mobile en menos de 5 minutos',
      'Tarjeta Visa débito sin costo de emisión',
      'Inversiones en FCI desde la app',
      'Transferencias y pagos 24/7',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Mejor tasa de ahorro',
  },
  {
    id: 'c8',
    categoria: 'cuentas',
    nombre: 'Cuenta DNI',
    banco: 'Banco Provincia',
    logo_domain: 'bancoprovincia.com.ar',
    descripcion: 'La billetera digital del banco provincial más grande de Argentina, con más de 6 millones de usuarios. Apertura solo con DNI.',
    puntuacion: 8.1,
    beneficios: [
      'Apertura solo con DNI, sin papeles',
      'Sin costo de mantenimiento',
      'Pago en comercios con QR',
      'Transferencias CBU/CVU 24/7',
      'Acceso a créditos del Banco Provincia',
      'Pago de impuestos y servicios de PBA',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Solo con DNI',
  },
  {
    id: 'c9',
    categoria: 'cuentas',
    nombre: 'Cuenta MODO',
    banco: 'MODO',
    logo_domain: 'modo.com.ar',
    descripcion: 'La plataforma de pagos de los bancos argentinos. Permite operar con la cuenta de cualquier banco adherido desde una sola app.',
    puntuacion: 7.8,
    beneficios: [
      'Pago con QR en más de 500.000 comercios',
      'Compatible con más de 30 bancos',
      'Sin costo de uso para particulares',
      'Transferencias instantáneas entre usuarios',
      'Cashback en comercios seleccionados (según campaña)',
      'Funciona con tu cuenta bancaria existente',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Multi-banco',
  },
  {
    id: 'c10',
    categoria: 'cuentas',
    nombre: 'Cuenta Macro',
    banco: 'Banco Macro',
    logo_domain: 'macro.com.ar',
    descripcion: 'Cuenta del banco privado más grande del interior de Argentina, con amplia red de sucursales y cajeros en todo el país.',
    puntuacion: 8.0,
    beneficios: [
      'Red de más de 500 sucursales en el interior',
      'Sin costo para cuentas sueldo',
      'Puntos Macro en compras con débito',
      'App Macro con pagos, transferencias y más',
      'Acceso a créditos hipotecarios y personales',
      'Descuentos en combustible YPF',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Líder en el interior',
  },
]

// ─────────────────────────────────────────────────────────────────
// PRÉSTAMOS PERSONALES
// IMPORTANTE: Las tasas (TNA/CFT) varían continuamente según BCRA.
// No se publican tasas específicas por riesgo de desactualización.
// ─────────────────────────────────────────────────────────────────
export const PRESTAMOS_MOCK: Producto[] = [
  {
    id: 'p1',
    categoria: 'prestamos',
    nombre: 'Préstamo Personal',
    banco: 'Banco Galicia',
    logo_domain: 'galicia.com.ar',
    descripcion: 'Préstamos personales con aprobación casi inmediata para clientes, con acreditación directa en cuenta y cuotas fijas en pesos.',
    puntuacion: 9.0,
    beneficios: [
      'Aprobación en pocos minutos para clientes',
      'Hasta $5.000.000 sin garantía (monto sujeto a perfil)',
      'Cuotas fijas en pesos, sin ajuste',
      'Acreditación en cuenta al instante',
      'Gestión 100% por app o homebanking',
      'Sin gastos de otorgamiento para clientes',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Aprobación rápida',
  },
  {
    id: 'p2',
    categoria: 'prestamos',
    nombre: 'Efectivo Ya',
    banco: 'Banco Nación',
    logo_domain: 'bna.com.ar',
    descripcion: 'Línea de crédito personal del banco más grande de Argentina con tasas reguladas y condiciones accesibles para jubilados y trabajadores.',
    puntuacion: 8.8,
    beneficios: [
      'Tasa de interés regulada por política del banco estatal',
      'Disponible para jubilados, pensionados y empleados',
      'Hasta 60 cuotas fijas',
      'Débito automático por CBU',
      'Sin necesidad de ser cliente previo',
      'Sucursales en todo el territorio nacional',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco estatal',
  },
  {
    id: 'p3',
    categoria: 'prestamos',
    nombre: 'Préstamo Personal',
    banco: 'BBVA Argentina',
    logo_domain: 'bbva.com.ar',
    descripcion: 'Crédito personal del grupo multinacional con hasta 72 cuotas, seguro de vida incluido y proceso 100% digital para clientes.',
    puntuacion: 8.7,
    beneficios: [
      'Hasta 72 cuotas fijas en pesos',
      'Seguro de vida sobre el saldo deudor incluido',
      'Hasta $8.000.000 (sujeto a perfil crediticio)',
      'Gestión por homebanking o app',
      'Tasa preferencial para clientes con sueldo domiciliado',
      'Pre-aprobación online instantánea',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Mayor plazo',
  },
  {
    id: 'p4',
    categoria: 'prestamos',
    nombre: 'Mercado Crédito',
    banco: 'Mercado Pago',
    logo_domain: 'mercadopago.com',
    descripcion: 'Crédito instantáneo basado en el historial de actividad en Mercado Libre y Mercado Pago. Sin papeles, 100% digital.',
    puntuacion: 8.5,
    beneficios: [
      'Aprobación 100% online, sin papeles ni garante',
      'Dinero en cuenta Mercado Pago al instante',
      'Monto ofrecido según historial de actividad',
      'Cuotas que se descuentan automáticamente del saldo',
      'Sin visita a sucursal ni requisitos burocráticos',
      'Disponible 24/7 desde la app',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: '100% digital',
  },
  {
    id: 'p5',
    categoria: 'prestamos',
    nombre: 'Crédito Personal',
    banco: 'Banco Macro',
    logo_domain: 'macro.com.ar',
    descripcion: 'Préstamos del banco del interior más grande de Argentina, con amplia red de sucursales y acceso para clientes de todo el país.',
    puntuacion: 8.3,
    beneficios: [
      'Hasta $4.000.000 (sujeto a perfil)',
      'Hasta 60 cuotas fijas',
      'Acreditación en cuenta Macro o CBU de otro banco',
      'Tasa preferencial para empleados públicos',
      'Más de 500 sucursales para atención',
      'Solicitud online y presencial',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Interior del país',
  },
  {
    id: 'p6',
    categoria: 'prestamos',
    nombre: 'Préstamo Ualá',
    banco: 'Ualá',
    logo_domain: 'uala.com.ar',
    descripcion: 'Préstamos personales 100% digitales con proceso simplificado y acreditación en cuenta Ualá. Sin papeles ni visitas presenciales.',
    puntuacion: 8.2,
    beneficios: [
      'Solicitud y aprobación 100% desde la app',
      'Sin visita a sucursal ni papeles',
      'Hasta $1.500.000 (sujeto a perfil)',
      'Cuotas fijas de 3 a 24 meses',
      'Acreditación inmediata en cuenta Ualá',
      'Sin gastos de otorgamiento',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Sin papeles',
  },
  {
    id: 'p7',
    categoria: 'prestamos',
    nombre: 'Préstamo Personal',
    banco: 'Santander Argentina',
    logo_domain: 'santander.com.ar',
    descripcion: 'Línea de préstamos personales del banco multinacional con tasa preferencial para clientes con sueldo domiciliado.',
    puntuacion: 8.0,
    beneficios: [
      'Hasta 72 cuotas en pesos',
      'Hasta $6.000.000 (sujeto a perfil)',
      'Seguro de vida incluido sobre el saldo',
      'Tasa preferencial para clientes select',
      'Gestión por homebanking Santander',
      'Red de más de 450 sucursales',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco multinacional',
  },
  {
    id: 'p8',
    categoria: 'prestamos',
    nombre: 'Crédito Provincia',
    banco: 'Banco Provincia',
    logo_domain: 'bancoprovincia.com.ar',
    descripcion: 'Créditos personales del segundo banco estatal más grande de Argentina, con condiciones especiales para empleados de la Provincia de Buenos Aires.',
    puntuacion: 7.9,
    beneficios: [
      'Condiciones preferenciales para empleados PBA',
      'Hasta 72 cuotas',
      'Débito directo de haberes para empleados',
      'Sin garante para empleados provinciales',
      'Solicitud online y en más de 300 sucursales',
      'Descuento automático del recibo de sueldo',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Empleados PBA',
  },
]

// ─────────────────────────────────────────────────────────────────
// SEGUROS DE AUTO
// IMPORTANTE: Los precios son referenciales. Varían por marca,
// modelo, año del vehículo, zona y perfil del conductor.
// ─────────────────────────────────────────────────────────────────
export const SEGUROS_MOCK: Producto[] = [
  {
    id: 's1',
    categoria: 'seguros',
    nombre: 'Auto Todo Riesgo',
    banco: 'Sancor Seguros',
    logo_domain: 'sancorseguros.com.ar',
    descripcion: 'La cobertura más completa del mercado, de la aseguradora más premiada de Argentina. Incluye granizo sin franquicia y vehículo de reemplazo.',
    puntuacion: 9.3,
    beneficios: [
      'Cobertura contra todo tipo de daños propios',
      'Robo y hurto total y parcial',
      'Granizo sin franquicia (cobertura especial)',
      'Vehículo de reemplazo hasta 15 días',
      'Grúa y auxilio mecánico 24hs',
      'App para denuncia y seguimiento de siniestros',
      'Cobertura de cristales sin franquicia',
    ],
    costo_mensual: 32000,
    url_afiliado: '#',
    activo: true,
    tag: 'Más completo',
  },
  {
    id: 's2',
    categoria: 'seguros',
    nombre: 'Auto Terceros Completo',
    banco: 'Galicia Seguros',
    logo_domain: 'galiciaseguros.com.ar',
    descripcion: 'Cobertura intermedia con robo, incendio y daños a terceros. Ideal para autos de hasta 5 años con una excelente relación precio-cobertura.',
    puntuacion: 9.0,
    beneficios: [
      'Robo y hurto total',
      'Incendio total y parcial',
      'Responsabilidad civil hacia terceros',
      'Asistencia en ruta 24hs',
      'Vehículo de cortesía por siniestro',
      'Gestión de siniestros 100% online',
    ],
    costo_mensual: 24000,
    url_afiliado: '#',
    activo: true,
    tag: 'Mejor relación precio',
  },
  {
    id: 's3',
    categoria: 'seguros',
    nombre: 'Auto Todo Riesgo',
    banco: 'Zurich Argentina',
    logo_domain: 'zurich.com',
    descripcion: 'Cobertura total de la aseguradora multinacional con presencia global y respaldo financiero de primer nivel.',
    puntuacion: 8.8,
    beneficios: [
      'Todo riesgo con franquicia reducida',
      'Robo total y parcial',
      'Cobertura de accesorios incorporados',
      'Asistencia en ruta y grúa',
      'Gestión de siniestros por app o web',
      'Red de talleres oficiales en todo el país',
    ],
    costo_mensual: 29000,
    url_afiliado: '#',
    activo: true,
    tag: 'Respaldo internacional',
  },
  {
    id: 's4',
    categoria: 'seguros',
    nombre: 'Auto Responsabilidad Civil',
    banco: 'Mercado Seguros',
    logo_domain: 'mercadopago.com',
    descripcion: 'La cobertura obligatoria al mejor precio del mercado, 100% digital. Póliza emitida al instante con gestión por WhatsApp.',
    puntuacion: 8.5,
    beneficios: [
      'Cumple con el seguro obligatorio por ley',
      'Precio competitivo del mercado',
      'Contratación 100% online en minutos',
      'Póliza digital disponible de inmediato',
      'Atención y denuncias por WhatsApp',
      'Sin inspección previa para autos nuevos',
    ],
    costo_mensual: 9500,
    url_afiliado: '#',
    activo: true,
    tag: 'Obligatorio · Precio bajo',
  },
  {
    id: 's5',
    categoria: 'seguros',
    nombre: 'Auto Terceros con Robo',
    banco: 'La Caja',
    logo_domain: 'lacaja.com.ar',
    descripcion: 'Una de las aseguradoras más tradicionales de Argentina con amplia red de productores y cobertura de robo parcial y total.',
    puntuacion: 8.4,
    beneficios: [
      'Robo total y parcial del vehículo',
      'Responsabilidad civil amplia',
      'Asistencia en ruta básica',
      'Descuento por buen historial de manejo',
      'Red de más de 3.000 productores asesores',
      'Atención telefónica y presencial',
    ],
    costo_mensual: 17500,
    url_afiliado: '#',
    activo: true,
    tag: 'Aseguradora tradicional',
  },
  {
    id: 's6',
    categoria: 'seguros',
    nombre: 'Auto Todo Riesgo',
    banco: 'MAPFRE Argentina',
    logo_domain: 'mapfre.com',
    descripcion: 'Cobertura todo riesgo del grupo multinacional español, con presencia en Argentina y atención personalizada en sucursales propias.',
    puntuacion: 8.6,
    beneficios: [
      'Todo riesgo con diferentes niveles de franquicia',
      'Robo total y parcial',
      'Cobertura de daños por granizo',
      'Asistencia en ruta y grúa 24hs',
      'Red de talleres propios MAPFRE',
      'App para seguimiento de siniestros',
    ],
    costo_mensual: 28000,
    url_afiliado: '#',
    activo: true,
    tag: 'Multinacional',
  },
  {
    id: 's7',
    categoria: 'seguros',
    nombre: 'Auto Terceros Completo',
    banco: 'Federación Patronal',
    logo_domain: 'federacionpatronal.com.ar',
    descripcion: 'Aseguradora argentina de capital nacional y presencia federal, especialmente fuerte en el interior del país.',
    puntuacion: 8.2,
    beneficios: [
      'Robo total y hurto',
      'Incendio total',
      'Responsabilidad civil',
      'Fuerte presencia en el interior del país',
      'Atención personalizada por productores locales',
      'Planes flexibles según zona geográfica',
    ],
    costo_mensual: 21000,
    url_afiliado: '#',
    activo: true,
    tag: 'Capital nacional',
  },
]
