import { Producto, Categoria } from './types'

export const CATEGORIAS: Categoria[] = [
  {
    id: '1',
    nombre: 'Tarjetas de Crédito',
    slug: 'tarjetas',
    descripcion: 'Encontrá la tarjeta con más beneficios para tu perfil',
    icono: '💳',
    color: '#1DB954',
    cantidad_productos: 24,
  },
  {
    id: '2',
    nombre: 'Cuentas Bancarias',
    slug: 'cuentas',
    descripcion: 'Cuentas con cashback, sin comisión y alta tasa',
    icono: '🏦',
    color: '#0ea5e9',
    cantidad_productos: 18,
  },
  {
    id: '3',
    nombre: 'Préstamos Personales',
    slug: 'prestamos',
    descripcion: 'Compará tasas y condiciones de los mejores préstamos',
    icono: '💰',
    color: '#f59e0b',
    cantidad_productos: 15,
  },
  {
    id: '4',
    nombre: 'Seguros',
    slug: 'seguros',
    descripcion: 'Auto, hogar y vida al mejor precio del mercado',
    icono: '🛡️',
    color: '#6366f1',
    cantidad_productos: 31,
  },
  {
    id: '5',
    nombre: 'Inversiones',
    slug: 'inversiones',
    descripcion: 'Plazos fijos, FCI y opciones para hacer rendir tu plata',
    icono: '📈',
    color: '#ec4899',
    cantidad_productos: 12,
  },
  {
    id: '6',
    nombre: 'Billeteras Virtuales',
    slug: 'billeteras',
    descripcion: 'Mercado Pago, Ualá, Naranja X y más comparadas',
    icono: '📱',
    color: '#8b5cf6',
    cantidad_productos: 9,
  },
]

export const TARJETAS_MOCK: Producto[] = [
  {
    id: '1',
    categoria: 'tarjetas',
    nombre: 'Visa Signature ICBC',
    banco: 'ICBC',
    descripcion: 'La mejor tarjeta para viajes internacionales con acceso a salas VIP y seguro de viaje incluido.',
    puntuacion: 9.4,
    beneficios: [
      'Acceso a salas VIP en aeropuertos',
      '3x puntos en compras internacionales',
      'Seguro de viaje automático',
      'Sin cargo el primer año',
      'Cuota 0% en viajes',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Mejor para viajes',
  },
  {
    id: '2',
    categoria: 'tarjetas',
    nombre: 'Mastercard Black Galicia',
    banco: 'Banco Galicia',
    descripcion: 'Tarjeta premium con los mejores beneficios en gastronomía, entretenimiento y devolución de efectivo.',
    puntuacion: 9.1,
    beneficios: [
      '5% cashback en gastronomía',
      '2x puntos en supermercados',
      'Descuentos en Netflix y Spotify',
      'Cuotas sin interés en más de 500 comercios',
      'Asistencia al viajero',
    ],
    costo_mensual: 2800,
    url_afiliado: '#',
    activo: true,
    red: 'Mastercard',
    tag: 'Más beneficios',
  },
  {
    id: '3',
    categoria: 'tarjetas',
    nombre: 'Naranja X',
    banco: 'Naranja X',
    descripcion: 'Ideal para el día a día con beneficios en comercios locales y sin costo de mantenimiento.',
    puntuacion: 8.7,
    beneficios: [
      'Sin costo de mantenimiento',
      '10% de descuento en más de 200 comercios',
      'Cuotas en todos los comercios adheridos',
      'App con gestión completa',
      'Reintegros en combustible',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Sin costo',
  },
  {
    id: '4',
    categoria: 'tarjetas',
    nombre: 'American Express Platinum',
    banco: 'American Express',
    descripcion: 'La tarjeta más exclusiva del mercado con beneficios únicos para el viajero frecuente.',
    puntuacion: 9.6,
    beneficios: [
      'Acceso ilimitado a salas VIP',
      'Créditos de viaje USD 200/año',
      'Concierge 24/7',
      'Upgrade automático en hoteles',
      'Seguro de compra global',
    ],
    costo_mensual: 8500,
    url_afiliado: '#',
    activo: true,
    red: 'Amex',
    tag: 'Premium',
  },
  {
    id: '5',
    categoria: 'tarjetas',
    nombre: 'Visa Clásica Santander',
    banco: 'Banco Santander',
    descripcion: 'La tarjeta de entrada perfecta con beneficios esenciales y cuotas en miles de comercios.',
    puntuacion: 8.2,
    beneficios: [
      'Cuotas en 6.000+ comercios',
      'Descuentos en supermercados adheridos',
      'Débito automático sin cargo',
      'App Santander incluida',
    ],
    costo_mensual: 1200,
    url_afiliado: '#',
    activo: true,
    red: 'Visa',
    tag: 'Para empezar',
  },
  {
    id: '6',
    categoria: 'tarjetas',
    nombre: 'Uala Mastercard',
    banco: 'Uala',
    descripcion: 'Tarjeta prepaga con cuenta virtual, sin costo y con beneficios en el ecosistema Ualá.',
    puntuacion: 8.5,
    beneficios: [
      'Sin costo de emisión ni mantenimiento',
      'Cashback en compras online',
      'Recarga instantánea',
      'Control de gastos en tiempo real',
      'Descuentos exclusivos Ualá',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    red: 'Mastercard',
    tag: 'Sin costo',
  },
]

export const CUENTAS_MOCK: Producto[] = [
  {
    id: 'c1',
    categoria: 'cuentas',
    nombre: 'Cuenta Mercado Pago',
    banco: 'Mercado Pago',
    descripcion: 'La cuenta digital más usada de Argentina con rendimiento diario automático y cashback en compras.',
    puntuacion: 9.3,
    beneficios: [
      'Rendimiento diario al 97% de la BADLAR',
      '3% cashback en compras con QR',
      'Sin costo de mantenimiento',
      'Tarjeta débito virtual y física',
      'Transferencias 24/7 sin límite',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Más popular',
  },
  {
    id: 'c2',
    categoria: 'cuentas',
    nombre: 'Cuenta Ualá',
    banco: 'Ualá',
    descripcion: 'Cuenta 100% digital con caja de ahorro remunerada y tarjeta Mastercard sin costo.',
    puntuacion: 8.9,
    beneficios: [
      'Rendimiento automático sobre saldo',
      'Tarjeta Mastercard sin costo',
      'Descuentos exclusivos en Ualá Market',
      'Envíos de dinero instantáneos',
      'Control total desde la app',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Sin costo',
  },
  {
    id: 'c3',
    categoria: 'cuentas',
    nombre: 'Cuenta Galicia Move',
    banco: 'Banco Galicia',
    descripcion: 'Cuenta del banco líder privado con beneficios exclusivos y acceso a todos los productos del banco.',
    puntuacion: 8.6,
    beneficios: [
      'Caja de ahorro remunerada',
      'Acceso a créditos preaprobados',
      'App con transferencias DEBIN',
      'Puntos en todas las compras',
      'Descuentos en comercios adheridos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco tradicional',
  },
  {
    id: 'c4',
    categoria: 'cuentas',
    nombre: 'Cuenta Personal Pay',
    banco: 'Personal Pay',
    descripcion: 'La cuenta de la telco más grande de Argentina con beneficios en servicios Personal.',
    puntuacion: 8.1,
    beneficios: [
      'Rendimiento diario',
      'Gigas de regalo en Personal',
      'Sin costo de mantenimiento',
      'Recarga de celular directa',
      'Descuentos en Personal Flow',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Nuevo',
  },
  {
    id: 'c5',
    categoria: 'cuentas',
    nombre: 'Cuenta BNA+',
    banco: 'Banco Nación',
    descripcion: 'La cuenta digital del banco más grande de Argentina, ideal para cobrar haberes y jubilaciones.',
    puntuacion: 7.8,
    beneficios: [
      'Acceso a créditos hipotecarios',
      'Tasa preferencial para jubilados',
      'Red de cajeros más grande del país',
      'Débito automático de servicios',
      'Turnos online',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Banco público',
  },
  {
    id: 'c6',
    categoria: 'cuentas',
    nombre: 'Cuenta Brubank',
    banco: 'Brubank',
    descripcion: 'El primer banco 100% mobile de Argentina con las mejores tasas en caja de ahorro.',
    puntuacion: 8.4,
    beneficios: [
      'Tasa de ahorro entre las más altas',
      'Sin costos de ningún tipo',
      'Apertura en 5 minutos desde el celular',
      'Tarjeta Visa débito gratuita',
      'Inversiones en FCI desde la app',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Mejor tasa',
  },
]

export const PRESTAMOS_MOCK: Producto[] = [
  {
    id: 'p1',
    categoria: 'prestamos',
    nombre: 'Préstamo Galicia',
    banco: 'Banco Galicia',
    descripcion: 'Préstamos personales con aprobación inmediata para clientes y acreditación en cuenta en minutos.',
    puntuacion: 9.0,
    beneficios: [
      'Aprobación en menos de 1 minuto',
      'Hasta $5.000.000 sin garantía',
      'Cuotas fijas en pesos',
      'Sin gastos de otorgamiento',
      'Acreditación inmediata',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Aprobación rápida',
  },
  {
    id: 'p2',
    categoria: 'prestamos',
    nombre: 'Efectivo Ya BNA',
    banco: 'Banco Nación',
    descripcion: 'Préstamos del banco nacional con las tasas más competitivas del mercado.',
    puntuacion: 8.7,
    beneficios: [
      'Tasa desde el 49% TNA',
      'Hasta $3.000.000',
      'Hasta 60 cuotas',
      'Para cualquier destino',
      'Sin necesidad de ser cliente',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Mejor tasa',
  },
  {
    id: 'p3',
    categoria: 'prestamos',
    nombre: 'Préstamo Mercado Crédito',
    banco: 'Mercado Pago',
    descripcion: 'Créditos instantáneos basados en tu historial de Mercado Libre y Mercado Pago.',
    puntuacion: 8.5,
    beneficios: [
      '100% online, sin papeles',
      'Dinero en cuenta al instante',
      'Monto según tu reputación',
      'Cuotas desde $5.000',
      'Sin garante ni aval',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Sin papeles',
  },
  {
    id: 'p4',
    categoria: 'prestamos',
    nombre: 'Préstamo Ualá',
    banco: 'Ualá',
    descripcion: 'Préstamos 100% digitales con proceso simple y acreditación en tu cuenta Ualá.',
    puntuacion: 8.2,
    beneficios: [
      'Todo desde la app',
      'Sin visita a sucursal',
      'Hasta $1.500.000',
      'Plazos de 3 a 24 cuotas',
      'Cuotas fijas en pesos',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Digital',
  },
  {
    id: 'p5',
    categoria: 'prestamos',
    nombre: 'Préstamo Santander',
    banco: 'Banco Santander',
    descripcion: 'Préstamos personales con flexibilidad de plazos y beneficios exclusivos para clientes.',
    puntuacion: 8.0,
    beneficios: [
      'Hasta 72 cuotas',
      'Hasta $8.000.000',
      'Seguro de vida incluido',
      'Tasa preferencial para clientes',
      'Gestión por homebanking',
    ],
    costo_mensual: 0,
    url_afiliado: '#',
    activo: true,
    tag: 'Mayor plazo',
  },
]

export const SEGUROS_MOCK: Producto[] = [
  {
    id: 's1',
    categoria: 'seguros',
    nombre: 'Auto Terceros Completo',
    banco: 'Galicia Seguros',
    descripcion: 'La cobertura más completa del mercado con asistencia en ruta 24/7 y vehículo de reemplazo.',
    puntuacion: 9.2,
    beneficios: [
      'Robo total y parcial',
      'Daños a terceros ilimitados',
      'Vehículo de reemplazo 15 días',
      'Asistencia en ruta 24/7',
      'Gestión de siniestros online',
    ],
    costo_mensual: 28000,
    url_afiliado: '#',
    activo: true,
    tag: 'Más completo',
  },
  {
    id: 's2',
    categoria: 'seguros',
    nombre: 'Auto Todo Riesgo',
    banco: 'Sancor Seguros',
    descripcion: 'Cobertura total contra todo tipo de daños con la aseguradora más premiada de Argentina.',
    puntuacion: 9.0,
    beneficios: [
      'Cobertura contra todo riesgo',
      'Cristales incluidos',
      'Granizo sin franquicia',
      'Grúa y auxilio mecánico',
      'App para gestión de siniestros',
    ],
    costo_mensual: 32000,
    url_afiliado: '#',
    activo: true,
    tag: 'Todo riesgo',
  },
  {
    id: 's3',
    categoria: 'seguros',
    nombre: 'Auto Responsabilidad Civil',
    banco: 'Mercado Seguros',
    descripcion: 'La cobertura obligatoria al mejor precio del mercado, 100% digital.',
    puntuacion: 8.4,
    beneficios: [
      'Obligatorio legal',
      'Precio competitivo',
      'Contratación 100% online',
      'Póliza digital instantánea',
      'Atención por WhatsApp',
    ],
    costo_mensual: 9500,
    url_afiliado: '#',
    activo: true,
    tag: 'Más económico',
  },
  {
    id: 's4',
    categoria: 'seguros',
    nombre: 'Auto Terceros con Robo',
    banco: 'Zurich Argentina',
    descripcion: 'Cobertura intermedia ideal para autos de más de 5 años con protección ante robo.',
    puntuacion: 8.7,
    beneficios: [
      'Robo total',
      'Daños a terceros',
      'Asistencia en ruta básica',
      'Descuento por buen historial',
      'Sucursales en todo el país',
    ],
    costo_mensual: 18500,
    url_afiliado: '#',
    activo: true,
    tag: 'Mejor relación precio',
  },
]
